on:
  push:
    branches:
      - main

name: ğŸš€ Deploy website on push

jobs:
  deploy:
    name: ğŸ‰ Deploy and Restart
    runs-on: ubuntu-latest

    steps:
      - name: ğŸšš Get latest code
        uses: actions/checkout@v4

      - name: ğŸ“‚ Deploy via FTP
        uses: SamKirkland/FTP-Deploy-Action@v4.3.5
        with:
          server: 20.81.128.40
          username: myopsre_app
          password: ${{ secrets.ftp_password }}
          port: 21
          protocol: "ftp"

      - name: ğŸ” SSH and run build/start
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: 20.81.128.40
          username: script
          key: ${{ secrets.ftp_password1 }}
          port: 22
          script: |
            cd /htdocs/app.myopsre.com
            npm install
            npm run build
            pm2 delete app-myopsre || true
            pm2 start npm --name "app-myopsre" -- start -- --port 4173
